- thousandeyes/provider.go
It appears this data source definition was re-added by a subsequent commit.
Removing it as it's now replaced with a resource definition.
> fix(provider): Remove old alert rules data source

- thousandeyes/data_source_thousandeyes_agent.go
- thousandeyes/resource_agent_to_agent.go
- thousandeyes/resource_ftp_server.go
- thousandeyes/resource_sip_server.go
- thousandeyes/resource_voice_call.go
- thousandeyes/schemas.go
Bulk change to fix existing schemas, add missing schemas, and bring value names in line with API.
This does happen to include a change to the name of the field use for agent names, which would impact existing config.  This is not strictly necessary at the moment, since the data sources have not been converted to use the consolidated schema definitions.  But this would be the only remaining case where Terraform field names diverge from the ThousandEyes API field names, so it is resolving an exceptional case as we approach full functionality/correctness.
> fix(schema) Update schemas to match API spec

- thousandeyes/data_source_thousandeyes_bgp_monitor.go
- thousandeyes/schemas.go
Values set for retrieved BGP monitor objects had wrong names.  This
corrects that.  Additionally, sets schema for BGP monitor ID to be
required.
> fix(bgp_monitor): Fix value name setting

- thousandeyes/schemas.go
Various schemas have been updated for correctness.
Notably, although an incorrect Elem definition for custom_headers is
provided, this field still does not work as is due to a limitation in
Terraform.  Maps of mixed types are not possible to use or define, and
therefore a workaround would be required to implement this field.  This
more correct definition is here in case this Terraform behavior changes
in the future.
> fix(schema): Correct schema definitions

- thousandeyes/data_source_thousandeyes_account_group.go
- thousandeyes/schemas.go
Values set for retrieved account group objects had wrong names.  This
corrects that.  Additionally, an extraneous schema definition for
shared_with_account_groups name value was removed.
> fix(account_group): Fix value name setting

- thousandeyes/resource_alert_rule.go
- thousandeyes/schemas.go
Unlike test updates which disallow certain non-updated fields, an update
for an alert rule requires more than just the updated fields.  This
will add the required fields to the update data.
A schema validation for the expression field is included.
> fix(alert_rule): Include required fields on update

- go.mod
- main.go
- thousandeyes/data_source_thousandeyes_account_group.go
- thousandeyes/data_source_thousandeyes_agent.go
- thousandeyes/data_source_thousandeyes_bgp_monitor.go
- thousandeyes/data_source_thousandeyes_integration.go
- thousandeyes/provider.go
- thousandeyes/resource_agent_to_agent.go
- thousandeyes/resource_agent_to_server.go
- thousandeyes/resource_alert_rule.go
- thousandeyes/resource_bgp.go
- thousandeyes/resource_dns_server.go
- thousandeyes/resource_dns_trace.go
- thousandeyes/resource_dnssec.go
- thousandeyes/resource_ftp_server.go
- thousandeyes/resource_http_server.go
- thousandeyes/resource_page_load.go
- thousandeyes/resource_sip_server.go
- thousandeyes/resource_voice.go
- thousandeyes/resource_voice_call.go
- thousandeyes/resource_web_transactions.go
- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
ThousandEyes API has cases where the existence or values of certain
fields are dependent on other fields.  Enhancing schema specification to
validate such fields requires new validation functions which are only
available in newer versions of the plugin SDK (ie: ConflictsWith,
ExactlyOneOf, AtLeastOneOf, RequiredWith).
This would have the consequence of losing support for terraform versions
below 0.12
> feat(sdk): Update sdk ver to add validation funcs

- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
This fixes schema validation for targetSipCredentials, which was
broken by a combination of newer version of Terraform with the new
plugin SDK.
Newer versions of Terraform do not permit declaring map schemas as
resources, meaning that there is no way to validate maps with elements
of disparate types or to validate specific key names in a map.  The
alternatives are to perform schema validtion manually elsewhere, or to
declare them as resources.  Since we already fall back to
resource declarations for lists of maps, repeating the practice seemed
like the least worst option.  Schema validation for this case is done by
declaring the type as a list with a maximum length of 1, and elements
declared as resources.
> Support building structs from list resources

- thousandeyes/data_source_thousandeyes_account_group.go
- thousandeyes/data_source_thousandeyes_agent.go
- thousandeyes/data_source_thousandeyes_bgp_monitor.go
- thousandeyes/data_source_thousandeyes_integration.go
- thousandeyes/provider.go
- thousandeyes/resource_agent_to_agent.go
- thousandeyes/resource_agent_to_server.go
- thousandeyes/resource_alert_rule.go
- thousandeyes/resource_bgp.go
- thousandeyes/resource_dns_server.go
- thousandeyes/resource_dns_trace.go
- thousandeyes/resource_dnssec.go
- thousandeyes/resource_ftp_server.go
- thousandeyes/resource_http_server.go
- thousandeyes/resource_label.go
- thousandeyes/resource_page_load.go
- thousandeyes/resource_sip_server.go
- thousandeyes/resource_voice.go
- thousandeyes/resource_voice_call.go
- thousandeyes/resource_web_transactions.go
- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
State for fields which were instances of other structs was previously
not saved correctly, due to Terraform being unable to match the JSON
field names to the correct schema.
Four pieces are involved in addressing this problem:
- on reads, build an equivalent map with correct names for resource
fields that happen to be structs, via type inspection as we do for
writes
- specify schema for details in nested fields
- handle reads for extraneous detail fields or inconsistent data types as special
cases
- make error checking for reads more thorough so these problems are not missed in the
future
> fix: Save remote state correctly for struct fields

- thousandeyes/resource_label.go
Currently label updates don't work if you want to do something like add an additional agent to a label resource
> fix(label): Include label name on update

- README.md
Our GH Org policy does not allow external collaborators in a repo, and we wanted to publicly acknowledge the extensive work by William Fleming, John Dyer, and Joshua Blanchard on the provider and SDK prior to ThousandEyes assuming maintenance of the project.
> Adding Acknowledgements to the README

- .goreleaser.yml
- README.md
- Fix Terraform logo link
- Update HTTP example. More examples to come in a dedicated examples/ directory.
- Drop gitter badge
- Drop link to Google Groups
- Drop dnsq tests, as they are no longer supported
- Add badges for sem version and license
- Change order of sections
Note that we will have a dedicated effort to update the documentation, add additional examples, and structure the documentation files it in a better way.
Edit: piggy-backing a commit to disable Windows ARM builds, as they're holding the pipeline. We can bring them back if there's a demand for them.
> docs: update README

- .github/workflows/test.yml
- .goreleaser.yml
- restore windows builds
- use go 1.17 on test.yaml
- drop darwin ignore on 386. We don't build that arch.
> ci: fix testing on pull requests 

- thousandeyes/schemas.go
- thousandeyes/util.go
The order of the agents does not matter. If we treat them as
schema.TypeList, then we enter a plan-apply loop with the plan
changing the order of the agents.
> fix: use TypeSet for Agents

- .github/workflows/release.yml
Hashicorp recommends no longer using their version:
https://github.com/hashicorp/ghaction-import-gpg/commit/58450e4f0672374a4c061f726f05be36b9be8ef5
> ci: fix gpg import

- .github/workflows/release.yml
Goreleaser is still failing:
https://github.com/thousandeyes/terraform-provider-thousandeyes/runs/7393734228
> ci: debug goreleaser

- .github/workflows/release.yml
There's an [open bug](https://github.com/goreleaser/goreleaser-action/issues/313) without much info.
> ci: try fixing gorelease using different versions

- thousandeyes/resource_label.go
Fix a crash on creation:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa748f2]
```
> fix: check for nil before dereferencing

- thousandeyes/data_source_thousandeyes_bgp_monitor.go
Fix crash:
```
panic: interface conversion: interface {} is int, not int64
```
> fix: properly cast to int64 in monitor_id

- thousandeyes/schemas.go
We need this to avoid state-change loops such as:
```
~ use_public_bgp          = false -> true
```
> fix: set use_public_bgp to false by default

- docs/resources/bgp.md
- docs/resources/voice.md
- examples/resources/thousandeyes_bgp/resource.tf
- examples/resources/thousandeyes_voice/resource.tf
- thousandeyes/schemas.go
Force domain in dns_server to always have a record type. According to
TE documentation:
> If no record type is specified, the test will default to an ANY record.
This does not play well with the Terraform state:
```
~ resource "thousandeyes_dns_server" "example_dns_server_test" {
~ domain                 = "www.thousandeyes.com ANY" -> "www.thousandeyes.com"
```
Additionally, this pull request updates some examples with the correct usage of `use_public_bgp`.
> fix: validate that domain has a record type suffix

- go.mod
- go.sum
Depend on thousandeyes-sdk-go version 2.0.0-beta.
> build: use te-sdk-go 2.0.0-beta

- go.mod
- go.sum
- thousandeyes/provider.go
This is hardcoded in the provider so we know what to expect and what to query to determine which API requests are coming from the terraform provider
> feat: sets HTTP client's User Agent to "ThousandEyes Terraform Provider"

- thousandeyes/resource_agent_to_agent.go
- thousandeyes/resource_agent_to_server.go
- thousandeyes/resource_alert_rule.go
- thousandeyes/resource_bgp.go
- thousandeyes/resource_dns_server.go
- thousandeyes/resource_dns_trace.go
- thousandeyes/resource_dnssec.go
- thousandeyes/resource_ftp_server.go
- thousandeyes/resource_http_server.go
- thousandeyes/resource_label.go
- thousandeyes/resource_page_load.go
- thousandeyes/resource_sip_server.go
- thousandeyes/resource_voice.go
- thousandeyes/resource_web_transactions.go
- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
Terraform was always passing a port on `agent_to_agent` and `agent_to_server` tests. This is fine for `agent_to_agent` as that test type does indeed require a port to be passed, but not for `agent_to_server` since `ICMP` based tests mustn't contain a port and `TCP` tests do not require the port to be passed (it'll default to 80 on ThousandEyes).
There are many approaches possible to fix this, but my constraints were:
* Keep using the common `schemas` variable
* Not separate `agent_to_server` resource into two resources: one for ICMP and one for TCP (which would allow us to create a specific port schema for each)
These constraints meant that the port had to be optional and not have default value for the `agent_to_server` resource. This meant that the schema definition for the port had to …
> fix: fixes agent_to_server ICMP tests which should not require a port

- docs/resources/agent_to_agent.md
- docs/resources/agent_to_server.md
- docs/resources/bgp.md
- docs/resources/dns_server.md
- docs/resources/dns_trace.md
- docs/resources/dnssec.md
- docs/resources/ftp_server.md
- docs/resources/http_server.md
- docs/resources/label.md
- docs/resources/page_load.md
- docs/resources/sip_server.md
- docs/resources/voice.md
- docs/resources/web_transaction.md
- thousandeyes/schemas.go
Additionally fixes type of builtin field in the agent groups (it was causing the provider to crash `panic: reflect.Set: value of type int is not assignable to type bool`).
This fixes https://github.com/thousandeyes/terraform-provider-thousandeyes/issues/105
TypeList is an ordered list, but users shouldn't have to worry about the order in which group blocks are placed in the resource:
```hcl
resource "thousandeyes_agent_to_server" "example" {
test_name      = "example"
interval       = 120
alerts_enabled = false
use_public_bgp = false
enabled = false
server = "www.thousandeyes.com"
agents {
agent_id = 1234
}
groups {
group_id = 1234
}
groups {
group_id = 5678
}
}
```
With `typeList`, terraform will care about the order of the groups, but with `typeSet`, order is not important (it's also a …
> fix: fixes group ordering, no longer required

- docs/index.md
- go.mod
- go.sum
- thousandeyes/provider.go
```
go vet ./... && echo && go test ./...
?   	github.com/thousandeyes/terraform-provider-thousandeyes	[no test files]
ok  	github.com/thousandeyes/terraform-provider-thousandeyes/thousandeyes	0.434s
```
Tested while working on the PR for the Go SDK:
Tested locally without overriding:
```
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - thousandeyes/thousandeyes in /Users/pedrorg/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
thousandeyes_alert_rule.test_alert_rule: Refreshing state... [id=4946549]
thousandeyes_agent_to_server.thousandeyes_agent_to_server_tcp_no_port: …
```
> feat: allows overriding the API Endpoint

- docs/resources/alert_rule.md
- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
This adds support for third party notifications within alert rules. This functionality was added to the Go SDK by a customer and external contributor, and we're adding the support to the terraform provider as it was a bit more complex than adding the support to the Go SDK. 
Tests are ok:
```
go vet ./... && echo && go test ./...
?   	github.com/thousandeyes/terraform-provider-thousandeyes	[no test files]
ok  	github.com/thousandeyes/terraform-provider-thousandeyes/thousandeyes	0.279s
```
Tested the provider with a local override:
```hcl
resource "thousandeyes_alert_rule" "thousandeyes_alert_rule_slack" {
rule_name = "Pedro-test: Alert Rule with third party integration"
alert_type = "End-to-End (Server)"
expression = "((loss >= 10%))"
minimum_sources = 5
rounds_violating_required = 10 …
```
> feat: Implement third party notification support within alert rules

- docs/resources/alert_rule.md
- thousandeyes/resource_alert_rule.go
- thousandeyes/schemas.go
- thousandeyes/util.go
* Fixes bug that was preventing the creation of alert rules with third party notifications but without email notification
* Fixes bug that was causing some fields (such as notifications and notifyOnClear) in alert rules to be reset when updating alert rules
* Fixes bug that was causing the recipient list to change on every run (it was using an ordered list)
ThousandEyes API documentation states that to update alert rules, the full list of fields must be sent. [Docs](https://developer.thousandeyes.com/v6/alerts/#/alert-rule-edit).
I should also note that while the fix is very simple, debugging these issues (apart from the recipient list order) was not easy and took me a full day basically, because there's still a lot about this codebase that I don't know. 
Tests are passing:
```
go vet …
```
> fix: fixes bugs related to alert rule notifications

- README.md
- docs/index.md
- examples/provider/provider.tf
Also updates the outdated link to the `installing a plugin` section of the terraform docs.
> docs: updates recommended provider version in our docs

- docs/resources/agent_to_agent.md
- docs/resources/agent_to_server.md
- docs/resources/bgp.md
- docs/resources/dns_server.md
- docs/resources/dns_trace.md
- docs/resources/dnssec.md
- docs/resources/ftp_server.md
- docs/resources/http_server.md
- docs/resources/label.md
- docs/resources/page_load.md
- docs/resources/sip_server.md
- docs/resources/voice.md
- docs/resources/web_transaction.md
- thousandeyes/schemas.go
Before releasing the BREAKING CHANGE that fixes them.
Docs were updated with `go generate`. Users should see the deprecation warning when planning and applying terraform.
We should release this before the breaking change here: https://github.com/thousandeyes/terraform-provider-thousandeyes/pull/125
> docs: marks the group/label attribute in tests as deprecated

- thousandeyes/data_source_thousandeyes_integration.go
Hello,
I've tried to setup ThousandEyes integrations and faced the issue:
```
2022-10-17T14:33:59.592-0600 [ERROR] vertex "thousandeyes_alert_rule.external_monitor_alert_rule" error: Missing required argument
2022-10-17T14:33:59.609-0600 [INFO]  backend/local: plan operation completed
╷
│ Error: Missing required argument
│
│   with thousandeyes_alert_rule.external_monitor_alert_rule,
│   on te_alert_rule.tf line 3, in resource "thousandeyes_alert_rule" "external_monitor_alert_rule":
│    3: resource "thousandeyes_alert_rule" "external_monitor_alert_rule" {
│
│ The argument "notifications.0.third_party.0.integration_type" is required,
│ but no definition was found.
```
I've added and successfully tested the missing argument. 
```
...
+ resource "thousandeyes_alert_rule" …
```
> fix: Adding required ThousandEyes integration type

- .github/ISSUE_TEMPLATE/issue-template.yml
The page will look like this (apologies for the screenshot cuts):
What do you think?
> docs: Adds issue template for bug reports

- thousandeyes/schemas.go
Keeping the validation in line with the developer docs:
> fix: Changed time limit allowed interval

- docs/resources/agent_to_server.md
- examples/resources/thousandeyes_agent_to_server/resource.tf
This (incorrect) content leads customers to believe they can simply flip the value to `true` and have BGP measurements enabled, which is not the case - they need to use the `bgp_measurements` flag first and augment it with either `bgp_monitors` or `use_public_bgp`.
> CAPS-15 Remove standalone `use_public_bgp = false` flag from agent-to-server example

- README.md
- docs/data-sources/account_group.md
- docs/data-sources/agent.md
- examples/data-sources/thousandeyes_account_group/data-source.tf
- thousandeyes/data_source_thousandeyes_agent.go
As requested within #128 by several users this adds ip addresses to the Agent DataSource:
```
Changes to Outputs:
+ agent_id     = 123213
+ agent_name   = "Vancouver, Canada"
+ ip_addresses = [
+ "155.313.108.19",
+ "155.313.108.23",
+ "155.313.108.15",
+ "2607:f6f3:3400:96::2:7",
+ "2607:f6f3:3400:96::2:4",
]
╷
```
> feat: added ip addresses to agent data source

- .github/workflows/test.yml
- thousandeyes/util.go
- thousandeyes/util_test.go
This fixes #111 .
It seems to conflict with the fix that was done [here](https://github.com/thousandeyes/terraform-provider-thousandeyes/pull/75) for #73. However, was trying out the scenarios from #73  locally:
- Create test with `alerts_enabled` set to `true` and without specifying any alert rule
- Create test with `alerts_enabled` set to `false` and with 2 alert rules, one of them being a default alert rule
- Remove one of the alert rules from a test which had 2 alert rules
and both Terraform plan/apply, as well as subsequent terraform plans, ran ok (and the subsequent terraform plans showed no changes). 
@raul-te not sure if you have any objection or know anything else that I should further test before merging this. Because it  does seems that filtering out the Default Alert Rules is …
> fix: default alert rule not being read

- .github/workflows/test.yml
- go.mod
- go.sum
- Update SDK version to 2.4.2 to add support for webhook notifications (see https://github.com/thousandeyes/thousandeyes-sdk-go/pull/120)
- Acceptance tests fail for forked PRs, add logic to skip them
> feat: add webhook notification support

- docs/resources/alert_rule.md
- thousandeyes/schemas.go
- thousandeyes/util.go
- thousandeyes/util_test.go
This will enable the use of webhook notifications within alerts using the recent SDK release.
Currently, you will receive an error if you set up alert rule notifications that use a custom webhook integration (for example, a Microsoft Teams integration data source) within Terraform.
Any feedback would be appreciated, thank you!
@joaomper-TE @shahid-te @pedro-te @phpinhei-te
> feat: adding support for webhook notifications

- docs/resources/alert_rule.md
- go.mod
- go.sum
- thousandeyes/acceptance_resources/alert_rule/create_test_with_alert_rule.tf
- thousandeyes/acceptance_resources/alert_rule/update_alert_rule.tf
- thousandeyes/resource_alert_rule.go
- thousandeyes/resource_alert_rule_test.go
- thousandeyes/schemas.go
fixes https://github.com/thousandeyes/terraform-provider-thousandeyes/issues/158
This issue is happening because we currently allow the alert rule <-> test association to be established from both perspectives. From the alert rule update perspective, it will clear any test association if the list of testIds is not sent in the request.
This PR changes the alert rule `test_ids` schema attribute to be [computed](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#computed) so that it is not considered in the TF plan but it's still retrieved from the alert rule get by id operation and passed along the alert rule update request.
Also, since the alert rule returns a field `tests` when getting by id and receives a field `testIds` when updating the alert rule, had to …
> fix: alert rule and tests association
