thousandeyes/terraform-provider-thousandeyes

LICENSE
go.mod
go.sum

* License moved to apache to match the go-thousandeyes lib
* updated to get fix for agent data source #4
* 0.3.1 fixed issues with agent data source
#4

feat(agent): updated go-thousandeyes -> 0.3.1 & Apache

---

.github/workflow/test.yml

* testing 
* build artifact for testing until we setup integration tests

chore(testing): build the provider on all pr's

---

README.md
go.mod
thousandeyes/provider.go
thousandeyes/resource_bgp.go
thousandeyes/resource_dns_trace.go
thousandeyes/resource_dnssec.go
thousandeyes/resource_sip_server.go
thousandeyes/resource_voice.go
thousandeyes/resource_voice_call.go
thousandeyes/util.go

Add support for test types: 
- BGP ( Fixes: #1 )
- DNS Trace
- DNSSEC
- SIP Server
- RTP Stream ("voice")
- Voice Call.

feat(resource): add support for several test types

---

thousandeyes/provider.go

* remove ftp as its failing to build
* resource doesnt exist yet

fix(ftp): remove ftp server from resource map

---

go.mod
thousandeyes/provider.go

* Adds support for sending account group ID
* Update go-thousandeyes to v0.8.1

feat(account-group): Add support for account group ID

---

thousandeyes/schemas.go

Support UDP for test type for agent to agent

Agent to Agent tests should support protocol UDP

---

go.mod
go.sum
thousandeyes/schemas.go
thousandeyes/util.go

rebase against upstream and bump go-thousandeyes to 1.1.1

rebase against upstream and bump go-thousandeyes to 1.1.1

---

go.mod
thousandeyes/data_source_thousandeyes_account_group.go
thousandeyes/provider.go

Add support for account groups data source, specifically to support the
SharedWithAccounts field on tests.

feat(accounts): Support account groups data source

---

.github/workflows/test.yml

feat(ci): fix ci build

---

thousandeyes/resource_sip_server.go

ThousandEyes test update behavior usually requires that updated fields be omitted.  The targetSipCredentials field is an exception, and this change accounts for this behavior.

fix(sip_server): Send fields necessary for update

---

.github/workflows/release.yml
terraform-registry-manifest.json

This contributions adds:
- The Terraform Registry manifest
- a fix for the `import-gpg` action

chore: add tf manifest

---

.github/workflows/release.yml
.github/workflows/test.yml

I can't get `crazy-max/ghaction-import-gpg` to [work](https://github.com/thousandeyes/terraform-provider-thousandeyes/runs/6803469728?check_suite_focus=true). I'll try with the example provided in the [scaffolding repository](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml).

ci: use config from scaffolding project

---

docs/resources/agent_to_agent.md
docs/resources/agent_to_server.md
docs/resources/alert_rule.md
docs/resources/bgp.md
docs/resources/dns_server.md
docs/resources/dns_trace.md
docs/resources/dnssec.md
docs/resources/ftp_server.md
docs/resources/http_server.md
docs/resources/label.md
docs/resources/page_load.md
docs/resources/sip_server.md
docs/resources/voice.md
docs/resources/voice_call.md
docs/resources/web_transaction.md

docs: go generate

---

LICENSE

Include 2022 copyright notice.

docs: Update copyright notice

---

.github/workflows/test.yml

Ensure go-generated files are up to date.

ci: ensure go-generated files are up to date

---

examples/provider/provider.tf
examples/resources/thousandeyes_agent_to_agent/resource.tf
examples/resources/thousandeyes_agent_to_server/resource.tf
examples/resources/thousandeyes_bgp/resource.tf
examples/resources/thousandeyes_dns_server/resource.tf
examples/resources/thousandeyes_http_server/resource.tf
examples/resources/thousandeyes_page_load/resource.tf
examples/resources/thousandeyes_sip_server/resource.tf
examples/resources/thousandeyes_voice/resource.tf

Add examples for the most used test resources.

docs: add resources examples

---

docs/index.md
templates/index.md.tmpl

Add instructions on how to get account group IDs available to the
current user.

docs: explain how to get AIDs

---

docs/resources/agent_to_agent.md
docs/resources/agent_to_server.md
docs/resources/dns_server.md
docs/resources/http_server.md
docs/resources/page_load.md
docs/resources/sip_server.md
docs/resources/voice.md
examples/resources/thousandeyes_agent_to_agent/resource.tf
examples/resources/thousandeyes_agent_to_server/resource.tf
examples/resources/thousandeyes_dns_server/resource.tf
examples/resources/thousandeyes_dns_trace/resource.tf
examples/resources/thousandeyes_dnssec/resource.tf
examples/resources/thousandeyes_ftp_server/resource.tf
examples/resources/thousandeyes_http_server/resource.tf
examples/resources/thousandeyes_page_load/resource.tf
examples/resources/thousandeyes_sip_server/resource.tf
examples/resources/thousandeyes_voice/resource.tf
examples/resources/thousandeyes_web_transaction/resources..tf

Hi Pedro,
Creating a new PR after making the changes you recommended in my previous PR #121 -
+ Squashed my local commits
+ Rebased local repo, added my changes to this commit and ran go generate

docs: updates and adds resources examples

---

.github/workflows/security.yml
go.mod

Create Github action for Go linter
Create Dependency Scan Github action
Create Github action for Terraform linter
Create CodeQl action for vulnerability scanning

feat: Security  improvements

---

go.mod
go.sum
thousandeyes/provider.go
thousandeyes/provider_test.go

SDK v3 module is temporarily replaced with local files until it is released

feat: add SDK v3 client

---

.github/workflows/security.yml

feat: update security config
